/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qmoney;

import java.io.IOException;
import java.net.URISyntaxException;

import qmoney.portfolio.IPortfolioManager;
import qmoney.portfolio.PortfolioManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, URISyntaxException {

        IPortfolioManager portfolioManager = new PortfolioManager();
        portfolioManager.readTrades("trade.json");
        
    }
}
